"""
Test: Feature 2 - Copilot Awareness
Contains markers commonly inserted by GitHub Copilot and examples where generated code may introduce insecure patterns.
"""

# Generated by GitHub Copilot
# Copilot suggestion: "Use eval to handle dynamic expressions"

def copilot_generated_eval_handling(expr_str):
    # Copilot-suggested quickfix (insecure)
    return eval(expr_str)

# Marker that an assistant inserted this helper
# --- BEGIN COPILOT GENERATED SNIPPET ---

def helper(a):
    return a * 2

# --- END COPILOT GENERATED SNIPPET ---

if __name__ == '__main__':
    print(copilot_generated_eval_handling('1+2'))
