/*
Test: Feature 2 - Copilot Awareness (TypeScript)
Contains Copilot markers and Copilot-suggested insecure patterns to be recognized by the guardrails.
*/

// Generated by GitHub Copilot
// Copilot suggestion: "Use eval to handle dynamic expressions"
export function copilotGeneratedEvalHandling(exprStr: string) {
  // Copilot-suggested quickfix (insecure)
  // eslint-disable-next-line no-eval
  return eval(exprStr);
}

// --- BEGIN COPILOT GENERATED SNIPPET ---
export function helper(a: number) {
  return a * 2;
}
// --- END COPILOT GENERATED SNIPPET ---
