/*
Test: Feature 2 - Copilot Awareness (Java)
Contains Copilot markers and Copilot-suggested insecure patterns that should be recognized by guardrails.
*/

public class feature2_copilot_awareness {
    // Generated by GitHub Copilot
    // Copilot suggestion: "Use ScriptEngine eval to handle dynamic expressions"

    public static Object copilotGeneratedEvalHandling(String expr) throws Exception {
        // Copilot-suggested quickfix (insecure)
        javax.script.ScriptEngine eng = new javax.script.ScriptEngineManager().getEngineByName("nashorn");
        return eng.eval(expr); // unsafe for untrusted input
    }

    // --- BEGIN COPILOT GENERATED SNIPPET ---
    public static int helper(int a) { return a * 2; }
    // --- END COPILOT GENERATED SNIPPET ---

    public static void main(String[] args) throws Exception {
        System.out.println(copilotGeneratedEvalHandling("1+2"));
    }
}
